### ISSUE TITLE
H2O with latest LibreSSL for ALPN support

### ISSUE THREAD

**Issue by VidhyaKumar** [tatsushid/h2o-rpm#5]
Will this be updated soon?

**Comment by tatsushid** [comment]
This package is build with `WITH_BUNDLED_SSL=on` build flag provided by H2O so it uses LibreSSL with ALPN which is bundled with H2O

**Comment by VidhyaKumar** [comment]
Oh okay, the version I installed bundled LibreSSL 2.4.5 and apparently ALPN was only supported in version 2.5.0 and above.

**Comment by tatsushid** [comment]
I checked [LibreSSL changelog](https://github.com/libressl-portable/portable/blob/master/ChangeLog) and found, ALPN support in 2.5.0 is `libtls` one but LibreSSL itself has supported it since 2.1.3 in `libssl` and H2O uses it so ALPN is supported in current H2O build.

Anyway, I don't plan to change bundled LibreSSL version. If you really want to do that, this is packaging repository so just cloning this, changing the build process and running it on your environment with Docker should make packages what you want.
